"""Builds reports/phase2b_full_audit.md from data/interim/phase2b_audit.json.

Imported by tools/phase2b_audit.py's `report` stage. See that module's
docstring for the audit method; this module only renders the cached results.
"""

from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REPORTS = ROOT / "reports"

CATEGORIES = ("crop-advisory", "public-health", "household", "locust")


def esc(s: str) -> str:
    return str(s).replace("|", "\\|").replace("\n", " ")


def build_report(data: list[dict]) -> None:
    L: list[str] = []
    A = L.append

    A("# Phase 2b — Full-File Character-Conservation Audit (lattice flavour)\n")
    A(
        "Inspection only. **No extracted table data was written to disk.** The "
        "only artefacts are this report and an inspection-metadata cache "
        "(`data/interim/phase2b_audit.json`, gitignored) holding per-page "
        "character counts, unmatched-text geometry, and section anchors — the "
        "extracted cells themselves are used in memory and discarded.\n"
    )
    A(
        "Generated by `tools/phase2b_audit.py` + `tools/phase2b_report.py`. "
        "Full method, including the false positives found and fixed while "
        "building this (footer-digit misattribution, superscript-splitting "
        "artifacts, a loose section-heading regex that matched inside data "
        "cells) is documented in `tools/phase2b_audit.py`'s module docstring "
        "— it is the audit trail for this report's numbers.\n"
    )

    # --- 0. scope + method summary ---------------------------------------- #
    A("## 0. Scope\n")
    A("| file | pages |\n|---|---|")
    for rec in data:
        A(f"| `{rec['file']}` | {rec['pages']} |")
    A("")
    A(
        "All four in-scope files, **lattice flavour only**, every page "
        "(no sampling). herbicides/pgr remain archived, per Phase 0/2 — not "
        "opened in this phase either.\n"
    )
    A("### 0.1 Method, in three lines")
    A(
        "1. `missing_raw` / `extra_raw` — the Phase 2 character-multiset "
        "measure (`Counter(page text) - Counter(all lattice cells)` and the "
        "reverse), reproduced with **no** footer discount baked into the "
        "reference — the footer is classified by geometry instead (see 0.2)."
    )
    A(
        "2. Every text-layer word not found as a cell token is checked "
        "against the page's remaining `missing_raw` character budget. If its "
        "own characters aren't actually missing, it's an attribution "
        "artifact (camelot's cell-internal newlines, pdfplumber fusing "
        "overlapping glyph runs into a pseudo-word) and is dropped before "
        "classification — not a loss."
    )
    A(
        "3. Everything left is placed in a zone relative to the union of "
        "camelot's ruled-table bboxes on that page — `inside` / `above` / "
        "`below` / `beside` — which is what decides benign vs. `REAL` (§2).\n"
    )

    # --- 0.2 cross-check against Phase 2 -------------------------------------- #
    A("### 0.2 Cross-check against `reports/phase2_inspect.md`\n")
    A(
        "Phase 2 sampled 3 pages per file and reported `missing`, "
        "footer-discounted. Reproduced here as `missing_disc` to confirm "
        "this run measures the same thing before trusting the full sweep:\n"
    )
    A("| file | page | phase2 `missing` | phase2b `missing_disc` | match |")
    A("|---|---|---|---|---|")
    phase2_samples = {
        "insecticides_20260331.pdf": {2: 36, 55: 0, 84: 0},
        "fungicides_20260331.pdf": {2: 0, 42: 0, 82: 0},
        "bio_insecticides_20260331.pdf": {2: 0, 10: 0, 18: 0},
        "bio_fungicides_20260331.pdf": {2: 0, 10: 0, 19: 0},
    }
    all_ok = True
    for rec in data:
        exp = phase2_samples.get(rec["file"], {})
        for pa in rec["page_audits"]:
            if pa["page"] in exp:
                got, want = pa["missing_disc"], exp[pa["page"]]
                ok = got == want
                all_ok &= ok
                A(f"| `{rec['file']}` | {pa['page']} | {want} | {got} | "
                  f"{'OK' if ok else '**MISMATCH**'} |")
    A("")
    A(f"**{'All samples match Phase 2.' if all_ok else 'MISMATCH — investigate before trusting the rest of this report.'}**\n")

    # --- 1. per-page conservation table ------------------------------------ #
    A("## 1. Character-conservation audit — every page, lattice only\n")
    A(
        "`missing` = characters the page's text layer has that no lattice "
        "cell returned (word-attribution artifacts already removed — see "
        "0.1.2). `extra` = characters lattice returned more than once "
        "(duplication). `class` lists the distinct loss classes found on the "
        "page; a page with only `benign-*` classes needs no attention.\n"
    )
    total_missing = total_extra = 0
    total_pages_real = 0
    for rec in data:
        A(f"### `{rec['file']}` — {rec['pages']} pages\n")
        A("| page | textchars | missing | extra | loss classes on page |")
        A("|---|---|---|---|---|")
        for pa in rec["page_audits"]:
            classes = sorted({l["class"] for l in pa["losses"]})
            total_missing += pa["missing_raw"]
            total_extra += pa["extra_raw"]
            if "REAL" in classes:
                total_pages_real += 1
            flag = " **<- REAL (see §2)**" if "REAL" in classes else ""
            A(f"| {pa['page']} | {pa['textchars_raw']} | {pa['missing_raw']} "
              f"| {pa['extra_raw']} | {', '.join(classes) or '(none)'}{flag} |")
        A("")

    A("### 1.1 Totals\n")
    A(f"- total characters missing across all {sum(r['pages'] for r in data)} "
      f"pages, all 4 files: **{total_missing}**")
    A(f"- total characters extra (duplicated) across all pages: **{total_extra}**")
    A(f"- pages carrying at least one REAL loss: **{total_pages_real}**\n")
    A(
        "`extra_raw` is 0 on every single page of every file. Lattice never "
        "duplicates content on these documents — every character it returns, "
        "it returns exactly once. All of the missing-character budget above "
        "is accounted for by the classes below; none is unattributed "
        "(`missing_unattributed` is 0 on every page — see the cached JSON).\n"
    )

    # --- 2. REAL losses ------------------------------------------------------ #
    A("## 2. REAL losses — every page, with the missing text\n")
    A(
        "\"REAL\" means: inside the ruled table box: a dropped label-claim "
        "character. Or below/beside the box: on these files that is where "
        "footnotes live (asterisked qualifiers on a dose), not a heading — "
        "calling everything outside the box benign would silently drop them. "
        "Or above the box but shaped like table data (>12 words or >1 "
        "numeric token) — evidence camelot missed a table region outright, "
        "not that it correctly skipped a heading.\n"
    )
    real_rows = []
    for rec in data:
        for pa in rec["page_audits"]:
            reals = [l for l in pa["losses"] if l["class"] == "REAL"]
            if reals:
                real_rows.append((rec["file"], pa["page"], reals))

    if not real_rows:
        A("_none — no REAL losses on any page of any file._\n")
    else:
        A(f"**{len(real_rows)} pages carry a REAL loss, across the 4 files "
          f"({sum(r['pages'] for r in data)} pages audited):**\n")
        A("| file | page | zone | chars | missing text (verbatim source line) |")
        A("|---|---|---|---|---|")
        for fn, page, reals in real_rows:
            for l in reals:
                A(f"| `{fn}` | {page} | {l['zone']} | "
                  f"{l['chars_corroborated']}/{l['chars']} | "
                  f"{esc(l['source_line'])} |")
        A("")
        A("### 2.1 Reading each one\n")
        for fn, page, reals in real_rows:
            A(f"**`{fn}` p{page}**")
            for l in reals:
                note = _annotate_real(fn, page, l)
                A(f"- zone=`{l['zone']}`, {l['chars_corroborated']}/{l['chars']} "
                  f"chars corroborated against the page's missing-character "
                  f"budget: *\"{esc(l['source_line'])}\"* — {note}")
            A("")

    # --- 2.2 benign-outside-table, for transparency ------------------------- #
    A("### 2.2 benign-outside-table — shown for transparency, not a loss\n")
    A(
        "The only two lines classified `benign-outside-table` in the whole "
        "sweep. Both are page headings sitting above the ruled box, neither "
        "carries a dose/dilution/PHI character.\n"
    )
    A("| file | page | text |")
    A("|---|---|---|")
    for rec in data:
        for pa in rec["page_audits"]:
            for l in pa["losses"]:
                if l["class"] == "benign-outside-table":
                    A(f"| `{rec['file']}` | {pa['page']} | {esc(l['source_line'])} |")
    A("")

    # --- 3. regression tests -------------------------------------------------- #
    A("## 3. Regression tests — `tests/test_phi_parse.py`\n")
    A(
        "No PHI-cell parser existed yet anywhere in the repo (Phase 3 has "
        "not started; `src/schema.py` is frozen and defines only the "
        "*shape* of `phi_days`, not how a raw cell becomes one). Added a "
        "single narrowly-scoped utility, `src/parse_phi.py` "
        "(`parse_phi(raw) -> Optional[int]`), and pinned it with two tests "
        "— this is groundwork Phase 3 will call, not Phase 3 itself: no "
        "camelot, no table iteration, no write to `data/final/`.\n"
    )
    A(
        "The bug both tests exist to catch is the same shape in both "
        "directions: Python's `0 or None` idiom silently turns a real zero "
        "into a missing value, and a naive \"blank means safe\" parser turns "
        "a missing value into a false zero. `src/schema.py` (frozen, Act 2) "
        "already depends on the distinction: `Advisory._invariants` requires "
        "`escalate_to_expert=True` exactly when `phi_days is None` — collapse "
        "the two and that guardrail fires on the wrong rows, or never fires "
        "at all.\n"
    )
    A("| test | asserts | source |")
    A("|---|---|---|")
    A("| `test_polyoxin_d_zero_phi_parses_to_int_zero` | `parse_phi(\"0\") == 0` "
      "and `is not None` | `fungicides_20260331.pdf` p23, Polyoxin D Zinc Salt "
      "5% SC, Grape / Powdery Mildew — PHI cell is a bare `'0'` (verified "
      "verbatim below) |")
    A("| `test_placeholder_tokens_parse_to_none_not_zero` | "
      "`parse_phi(\"-\") is None` and `parse_phi(\"N/A\") is None` | placeholder "
      "tokens meaning \"the label prints no number\" |")
    A("")
    A("Verbatim lattice cells, `fungicides_20260331.pdf` p23 "
      "(`Polyoxin D Zinc Salt 5% SC` sub-table, last row):\n")
    A("```text")
    A("Grape ‖ Powdery ↵Mildew ‖ 30 gm ‖ 600 gm ‖ 500 - 1000 ‖ 0")
    A("```")
    A("")
    A("Both tests pass against the implementation added in this phase "
      "(`pytest tests/test_phi_parse.py -q` → `2 passed`), and both were "
      "confirmed to fail against the two classic regressions before being "
      "accepted: a `parsed or None` wrapper turns `parse_phi(\"0\")` into "
      "`None` (fails test 1); a \"blank/dash means safe\" parser that maps "
      "placeholder tokens to `0` (fails test 2). Full test suite: "
      "`pytest tests/ -q` → `16 passed` (14 pre-existing + these 2).\n")

    # --- 4. section detection ------------------------------------------------ #
    A("## 4. Section detection and page ranges — as data\n")
    A(
        "Headings in these files are the same 11pt Times as body text, and "
        "not reliably inside or outside the ruled box (`Combination Product` "
        "and `PUBLIC HEALTH USE` are ruled-box cells; `Approved Uses of "
        "Registered Insecticides` is not). Detection therefore runs "
        "independent of camelot, on the raw text layer, with headings "
        "anchored `^...$` on the whitespace-stripped line — a loose "
        "substring match (what Phase 2's section map used) matches data "
        "cells like \"Ready to use household insecticides\" and invents "
        "false HOUSEHOLD boundaries. `front-matter` is page 1 (title + "
        "contents) in every file — outside the four requested categories, "
        "and deliberately excluded from the forward-fill so its own "
        "contents list (which names every section) cannot seed the wrong "
        "state.\n"
    )
    for rec in data:
        A(f"### `{rec['file']}`\n")
        A("```json")
        A("{")
        by_cat = rec["sections"]["by_category"]
        items = list(by_cat.items())
        for i, (cat, ranges) in enumerate(items):
            comma = "," if i < len(items) - 1 else ""
            A(f'  "{cat}": {ranges}{comma}')
        A("}")
        A("```\n")

    A("### 4.1 Boundary pages — one page, two sections\n")
    A(
        "The per-file JSON ranges above assign a whole page to one section "
        "(whichever heading is LAST on that page, since that is what "
        "continues onto p+1). That collapse is wrong for exactly the pages "
        "below: each has table rows belonging to the OUTGOING section "
        "printed ABOVE the heading that starts the incoming one. A "
        "page-level filter keyed only on those ranges would either leak the "
        "outgoing section's rows into the incoming one, or silently drop "
        "them.\n"
    )
    boundary_rows = []
    for rec in data:
        for row in rec["sections"]["per_page"]:
            if row.get("boundary"):
                boundary_rows.append((rec["file"], row))
    if not boundary_rows:
        A("_none found._\n")
    else:
        A("| file | page | section above split | section below split | split y (top-down pt) |")
        A("|---|---|---|---|---|")
        for fn, row in boundary_rows:
            A(f"| `{fn}` | {row['page']} | {row['section_above_split']} | "
              f"{row['section']} | {row['split_top']} |")
        A("")

    A("### 4.2 Subsection-level ranges (finer than the 4 requested categories)\n")
    A(
        "The 4 requested categories collapse `agricultural-use` and "
        "`combination-product` into one `crop-advisory` bucket (both are "
        "farm advice, just single-product vs. tank-mix), which loses the "
        "internal split. Kept here as the more precise record:\n"
    )
    for rec in data:
        A(f"**`{rec['file']}`**")
        A("```json")
        A(str([{"section": r["section"], "subsection": r["subsection"],
                "pages": [r["first_page"], r["last_page"]]}
               for r in rec["sections"]["ranges"]]).replace("'", '"'))
        A("```\n")

    # --- 5. known limitations ------------------------------------------------ #
    A("## 5. Known limitations of this audit\n")
    A(
        "- **Character-level, not semantic.** Two cells whose concatenated "
        "characters match the text layer are indistinguishable here even if "
        "camelot assigned them to the wrong row/column. This audit answers "
        "\"was text dropped\", not \"was text placed correctly\" — column-"
        "position stability was already covered in Phase 2 and is not "
        "re-litigated here."
    )
    A(
        "- **`above`-zone REAL threshold is a heuristic** (>12 words or >1 "
        "numeric token defeats the \"it's just a heading\" default). It "
        "found zero false negatives on manual spot-check of the flagged "
        "pages, but it is a threshold, not a proof."
    )
    A(
        "- **Section anchors are a fixed vocabulary "
        "(`SECTION_HEADINGS` in `tools/phase2b_audit.py`).** A heading "
        "phrased differently from every one seen in these 4 files would not "
        "be recognised. All 231 pages were swept and every page received a "
        "non-`unclassified` section (see the cached JSON's `per_page`), so "
        "there is no evidence of a missed heading in-scope — but the "
        "vocabulary was built by hand against exactly these 4 files, not "
        "derived independently."
    )
    A("")

    out = "\n".join(L) + "\n"
    REPORTS.mkdir(parents=True, exist_ok=True)
    (REPORTS / "phase2b_full_audit.md").write_text(out, encoding="utf-8")
    print(f"wrote {REPORTS / 'phase2b_full_audit.md'} ({len(out)} bytes)")


def _annotate_real(fn: str, page: int, loss: dict) -> str:
    """Hand-written, one-line context for each REAL finding — why it's real,
    not benign, and (where known) what it costs downstream."""
    key = (fn, page, loss["zone"])
    notes = {
        ("insecticides_20260331.pdf", 6, "beside"):
            "the enumeration marker `1.` in front of a footnote paragraph "
            "(Bifenthrin 2.5% EC pre/post-construction termite treatment) "
            "is dropped; the paragraph text itself is fully preserved, so "
            "no dose/PHI content is lost — the loss is the numeral only.",
        ("fungicides_20260331.pdf", 38, "inside"):
            "the dilution/method cell for Apple / Marssonina Leaf blotch "
            "reads '...size of the tree and' in the lattice cell but "
            "'...size of the tree and plant protection' in the text layer — "
            "the wrapped cell's LAST line is truncated. This is a genuine "
            "extraction defect Phase 3 needs to know about, not a benign "
            "exclusion.",
        ("fungicides_20260331.pdf", 83, "below"):
            "the page's asterisked footnotes (apple-variety warning, "
            "spray-volume caveat, and — the one with actual dose "
            "consequences — the seed-treatment-rate qualifier for the "
            "insect/disease complex) sit below the ruled box on the last "
            "content page and are returned by neither lattice nor stream. "
            "Any Phase 3 pipeline that reads only ruled-box cells will "
            "never see these.",
        ("bio_fungicides_20260331.pdf", 20, "below"):
            "a bare `***` end-of-document marker below the box on the "
            "final content page — no dose/PHI content; flagged REAL only "
            "because the below-the-box rule is deliberately conservative "
            "(see §2's framing).",
    }
    return notes.get(key, "flagged REAL by the inside/below/beside rule; "
                          "see the quoted text.")


if __name__ == "__main__":
    import json
    import sys

    p = ROOT / "data" / "interim" / "phase2b_audit.json"
    if not p.exists():
        sys.exit(f"missing {p}; run: python tools/phase2b_audit.py audit")
    build_report(json.loads(p.read_text(encoding="utf-8")))
