"""Render reports/phase3_step2b_phantom.md from the Step 2b diagnosis JSON.

Reads data/interim/phase3_step2b_phantom.json (written by
tools/phase3_step2b_phantom.py) and formats it for manual judgement. No
analysis happens here — this file only presents. Run the diagnosis first.
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
JSON_IN = ROOT / "data" / "interim" / "phase3_step2b_phantom.json"
MD_OUT = ROOT / "reports" / "phase3_step2b_phantom.md"

SHORT = {
    "insecticides_20260331_raw.csv": "insecticides",
    "fungicides_20260331_raw.csv": "fungicides",
    "bio_insecticides_20260331_raw.csv": "bio_insecticides",
    "bio_fungicides_20260331_raw.csv": "bio_fungicides",
}

PREV_FIELDS = [
    ("crop", "crop"),
    ("pest_or_disease", "pest_or_disease"),
    ("dose_ai", "dose_ai"),
    ("dose_formulation", "dose_formulation"),
    ("dilution_water", "dilution_water"),
    ("waiting_period_phi", "waiting_period_phi"),
    ("method", "method"),
]


def cell(s: str | None, limit: int = 400) -> str:
    """Inline-code a value for a markdown table, keeping it on one line."""
    if s is None:
        return "—"
    if s == "":
        return "*(empty)*"
    s = s.replace("|", "\\|").replace("\n", " ")
    if len(s) > limit:
        s = s[:limit] + " …"
    return f"`{s}`"


def render_candidate(c: dict, short: str, lines: list[str]) -> None:
    frag = c["fragment_column"] or "/".join(c["own_columns"]) or "(none)"
    lines.append(
        f"#### `{short}` p{c['page']} r{c['row_index']} "
        f"— fragment in **{frag}**"
    )
    lines.append("")
    lines.append(
        f"csv_index {c['csv_index']} · kind `{c['assignment_kind']}` · "
        f"{c['n_segments']} own segment(s) · "
        f"{len(c['empty_dose_cols'])}/4 dose cols empty · "
        f"scope crop: **{c['scope_crop'] or '—'}**"
    )
    lines.append("")
    lines.append(f"active_ingredient: {cell(c['active_ingredient'])}")
    lines.append("")
    lines.append("| | crop | pest_or_disease | dose_ai | dose_form | dilution | PHI | method |")
    lines.append("|---|---|---|---|---|---|---|---|")

    p = c["prev"]
    if p is not None:
        lines.append(
            f"| **prev** p{p['page']} r{p['row_index']} | "
            + " | ".join(cell(p[k]) for _, k in PREV_FIELDS) + " |"
        )
    crop_note = "" if c["crop_is_own"] else " *(fwd-filled)*"
    lines.append(
        f"| **THIS** p{c['page']} r{c['row_index']} | "
        + cell(c["crop"]) + crop_note + " | "
        + cell(c["pest_or_disease"]) + " | "
        + " | ".join(cell("") for _ in range(4)) + " | "
        + cell(c["method"]) + " |"
    )
    lines.append("")
    lines.append(f"- this row's own text: {cell(c['raw_row_text'])}")
    if p is not None:
        lines.append(f"- prev row's own text: {cell(p['raw_row_text'])}")
    lines.append("")


def render_partial(c: dict, short: str, lines: list[str]) -> None:
    frag = c["fragment_column"] or "/".join(c["own_columns"]) or "(none)"
    p = c["prev"]
    lines.append(
        f"#### `{short}` p{c['page']} r{c['row_index']} "
        f"— own columns: **{frag}** · empty: {', '.join(c['empty_dose_cols'])}"
    )
    lines.append("")
    lines.append(
        f"csv_index {c['csv_index']} · kind `{c['assignment_kind']}` · "
        f"{c['n_segments']} own segment(s) · scope crop: **{c['scope_crop'] or '—'}**"
    )
    lines.append("")
    lines.append(f"- this row's own text: {cell(c['raw_row_text'])}")
    if p is not None:
        lines.append(f"- prev row (p{p['page']} r{p['row_index']}) own text: {cell(p['raw_row_text'])}")
    lines.append("")


def main() -> None:
    d = json.loads(JSON_IN.read_text(encoding="utf-8"))
    t = d["totals"]
    L: list[str] = []

    L.append("# Phase 3, Step 2b — Phantom Continuation Rows (DIAGNOSIS ONLY)")
    L.append("")
    L.append(
        "**Nothing merged, nothing dropped, no raw CSV rewritten.** The only "
        "artefacts are this report and `data/interim/phase3_step2b_phantom.json` "
        "(gitignored). Generated by `tools/phase3_step2b_phantom.py` + "
        "`tools/phase3_step2b_report.py`; the detection net and its two structural "
        "exclusions are documented in the former's module docstring."
    )
    L.append("")

    L.append("## 0. The defect")
    L.append("")
    L.append(
        "When a table cell wraps across a page break, camelot returns the fragment "
        "on page N+1 as its own row. Step 2's forward-fill then supplies `crop` and "
        "`active_ingredient` from the carry, and the fragment materialises as a "
        "complete-looking advisory row with empty dose columns — a **(crop, pest) "
        "pair the source never registered as a row**."
    )
    L.append("")
    L.append(
        "No existing check sees it: the Step 2 hard assertion counts source rows and "
        "the fragment *is* a real camelot row; the phase-2b character-conservation "
        "audit finds every character present on both sides (conservation is "
        "necessary but not sufficient for correct ROW segmentation); the bold "
        "detector sees regular-weight body text, which is what it is."
    )
    L.append("")

    L.append("## 1. Totals")
    L.append("")
    L.append("| class | count |")
    L.append("|---|---|")
    L.append(f"| first-row-of-page, **all four** dose cols empty | **{t['all_dose_empty']}** |")
    L.append(f"| first-row-of-page, **some but not all** dose cols empty | **{t['partial_dose_empty']}** |")
    L.append(f"| excluded — `chemical_header`/`column_header` (dose-empty by construction) | {t['excluded_non_data_kind']} |")
    L.append(f"| excluded — non-crop-advisory sections (all semantic cols blank by construction) | {t['excluded_non_crop_advisory']} |")
    L.append("")
    L.append(
        "The two exclusions are structural, not judgement: a header row has every "
        "semantic column blank by construction, and a public-health/household/locust "
        "row carries `raw_row_text` only — a fragment there cannot fabricate a label "
        "claim because there is no claim to fabricate."
    )
    L.append("")

    L.append("## 2. Which column the fragment occupies")
    L.append("")
    L.append(
        "**Fragments appear in MORE THAN ONE column.** This is the finding that "
        "changes the fix: a single pest-column merge rule is not sufficient."
    )
    L.append("")
    L.append("| fragment column | count |")
    L.append("|---|---|")
    for k, v in t["fragment_columns"].items():
        label = "*(multi-segment or no own column — see §5)*" if k == "MULTI/NONE" else f"`{k}`"
        L.append(f"| {label} | {v} |")
    L.append("")
    L.append(
        "`own_columns` is computed from the row's OWN segments (`raw_row_text`), not "
        "from its populated columns — `crop` is forward-filled on nearly every one of "
        "these rows and would otherwise dominate the signature falsely."
    )
    L.append("")

    L.append("## 3. Scope-crop exposure")
    L.append("")
    L.append(
        "Counted across both classes, using an explicit alias map "
        "(`Red gram`/`Pigeon pea` = tur, `Bengal gram`/`Chickpea` = gram, "
        "`Grapes` = grape). `Green gram` (moong) and `Black gram`/`Urd bean` (urad) "
        "are deliberately NOT folded into scope `gram`, which is chickpea only."
    )
    L.append("")
    L.append("| scope crop | fragments |")
    L.append("|---|---|")
    for k, v in t["scope_crop_hits"].items():
        L.append(f"| {k} | {v} |")
    L.append(f"| **total on scope crops** | **{sum(t['scope_crop_hits'].values())}** |")
    L.append("")

    L.append("## 4. The list — all four dose columns empty")
    L.append("")
    L.append(
        "Each entry prints the previous page's last row in full, for continuation-vs-"
        "genuine judgement. `*(fwd-filled)*` marks a `crop` that came from the carry, "
        "not from this row's own text."
    )
    L.append("")
    for fn, f in d["files"].items():
        cands = f["all_dose_empty"]
        if not cands:
            continue
        L.append(f"### `{SHORT[fn]}` — {len(cands)} candidate(s)")
        L.append("")
        for c in cands:
            render_candidate(c, SHORT[fn], L)

    L.append("## 5. The list — SOME but not all dose columns empty")
    L.append("")
    L.append(
        "Requirement 4. Most of these are multi-segment rows that are plainly genuine "
        "(the source simply prints no value in one column), but the class does extend "
        "here — see the crop-column wrap noted in §6."
    )
    L.append("")
    for fn, f in d["files"].items():
        cands = f["partial_dose_empty"]
        if not cands:
            continue
        L.append(f"### `{SHORT[fn]}` — {len(cands)} candidate(s)")
        L.append("")
        for c in cands:
            render_partial(c, SHORT[fn], L)

    L.append("## 6. Not done here")
    L.append("")
    L.append(
        "No merge, no drop, no change to `src/schema.py`, no change to the Step 2 "
        "extractor or its raw CSVs. Step B (the merge rule) is deferred until this "
        "list has been reviewed."
    )
    L.append("")

    MD_OUT.write_text("\n".join(L), encoding="utf-8")
    print(f"wrote {MD_OUT.relative_to(ROOT)}  ({len(L)} lines)")


if __name__ == "__main__":
    main()
